//Autogenerated by ue4ModuleCreator
//https://github.com/okanag/unrealModuleCreator

#pragma once

#include "CoreMinimal.h"
#include "ModuleManager.h"


class FQuestSystemCommonsModule : public IModuleInterface
{
public:
	virtual void StartupModule() override;
	virtual void ShutdownModule() override;
};