//Autogenerated by ue4ModuleCreator
//https://github.com/okanag/unrealModuleCreator

#include "QuestSystemCommons.h"


void FQuestSystemCommonsModule::StartupModule()
{
}

void FQuestSystemCommonsModule::ShutdownModule()
{
}

IMPLEMENT_MODULE(FQuestSystemCommonsModule, QuestSystemCommons);